name: loginsignup_new
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  get: ^4.6.1
  http: ^1.2.2
  html: ^0.15.5
  encrypt: ^5.0.3
  crypto: ^3.0.6
  shared_preferences: ^2.3.5
  percent_indicator: ^4.2.4
  fl_chart: ^0.70.0
  process_run: 1.2.2+1
  dart_ping: ^9.0.1
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  syncfusion_flutter_gauges: ^28.2.5
  url_launcher: ^6.3.1
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.1
  speed_test_dart: ^1.0.5+0
  flutter_internet_speed_test: ^1.5.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.2
  badges: ^2.0.0
  mc_custom_notification: ^0.0.8
  overlay_support: ^2.1.0
  timezone: ^0.9.2
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  jwt_decoder: ^2.0.1
  #auto_start_flutter: ^0.1.0
  sqflite: ^2.2.0
  path: ^1.8.2  
  rive: ^0.13.20
  flutter_slidable: ^4.0.0
  

 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/
